name: http2_client
version: 1.0.0
description: A package:http BaseClient that speaks HTTP/2, and can maintain connections.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/http2_client
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  http: ^0.12.0
  http2: ^1.0.0
  http_parser: ^3.0.0
  tuple: ^1.0.0
dev_dependencies:
  angel_framework: ^2.0.0-alpha
  cli_repl:
  path:
  pedantic: ^1.0.0
  test: ^1.0.0